"""
Unit tests for PostgresManager.insert() return type and behavior.

Tests the tuple return (count, inserted_articles), RETURNING clause,
metadata correctness, deduplication, and ON CONFLICT modes.
"""

from datetime import datetime, timezone
from unittest.mock import MagicMock, patch, call

import pytest

from govbr_scraper.models.news import NewsInsert
from govbr_scraper.storage.postgres_manager import PostgresManager


# =============================================================================
# Fixtures
# =============================================================================


@pytest.fixture
def sample_news():
    """Sample NewsInsert objects for testing."""
    return [
        NewsInsert(
            unique_id="mec-2026-01-01-noticia-1",
            agency_id=1,
            agency_key="mec",
            agency_name="Ministério da Educação",
            title="Notícia 1",
            published_at=datetime(2026, 1, 1, 12, 0, tzinfo=timezone.utc),
        ),
        NewsInsert(
            unique_id="mds-2026-01-02-noticia-2",
            agency_id=2,
            agency_key="mds",
            agency_name="Ministério do Desenvolvimento Social",
            title="Notícia 2",
            published_at=datetime(2026, 1, 2, 15, 30, tzinfo=timezone.utc),
        ),
    ]


@pytest.fixture
def mock_pool():
    """Mock connection pool."""
    mock_conn = MagicMock()
    mock_cursor = MagicMock()
    mock_conn.cursor.return_value = mock_cursor

    mock_pool = MagicMock()
    mock_pool.getconn.return_value = mock_conn

    return mock_pool, mock_conn, mock_cursor


@pytest.fixture
def pg_manager(mock_pool):
    """PostgresManager with mocked pool."""
    pool_obj, _, _ = mock_pool
    manager = PostgresManager.__new__(PostgresManager)
    manager._connection_string = "postgresql://test"
    manager.pool = pool_obj
    manager._agencies_by_key = {}
    manager._agencies_by_id = {}
    manager._themes_by_code = {}
    manager._themes_by_id = {}
    manager._cache_loaded = False
    return manager


# =============================================================================
# Return type
# =============================================================================


class TestInsertReturnType:
    """Tests for insert() return type."""

    @pytest.mark.parametrize("returned_ids,expected_count", [
        ([("mec-2026-01-01-noticia-1",), ("mds-2026-01-02-noticia-2",)], 2),
        ([("mec-2026-01-01-noticia-1",)], 1),
        ([], 0),
    ], ids=["two-inserts", "one-insert", "all-conflicts"])
    def test_return_value_structure_and_count(self, pg_manager, mock_pool, sample_news, returned_ids, expected_count):
        """insert() returns (int, list[dict]) with count matching RETURNING rows."""
        _, _, mock_cursor = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=returned_ids,
        ):
            result = pg_manager.insert(sample_news)

        # Verify structure
        assert isinstance(result, tuple)
        assert len(result) == 2
        assert isinstance(result[0], int)
        assert isinstance(result[1], list)

        # Verify count matches RETURNING rows
        count, articles = result
        assert count == expected_count
        assert len(articles) == expected_count


# =============================================================================
# Query content
# =============================================================================


class TestInsertQuery:
    """Tests for the SQL query generated by insert()."""

    def test_query_contains_returning(self, pg_manager, mock_pool, sample_news):
        """INSERT query includes RETURNING unique_id."""
        _, _, mock_cursor = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[("mec-2026-01-01-noticia-1",)],
        ) as mock_exec:
            pg_manager.insert(sample_news)

        query = mock_exec.call_args[0][1]
        assert "RETURNING unique_id" in query

    def test_do_nothing_query(self, pg_manager, mock_pool, sample_news):
        """Default mode uses ON CONFLICT DO NOTHING."""
        _, _, mock_cursor = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[],
        ) as mock_exec:
            pg_manager.insert(sample_news, allow_update=False)

        query = mock_exec.call_args[0][1]
        assert "ON CONFLICT (unique_id) DO NOTHING" in query

    def test_allow_update_query(self, pg_manager, mock_pool, sample_news):
        """allow_update=True uses ON CONFLICT DO UPDATE SET."""
        _, _, mock_cursor = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[("mec-2026-01-01-noticia-1",)],
        ) as mock_exec:
            pg_manager.insert(sample_news, allow_update=True)

        query = mock_exec.call_args[0][1]
        assert "DO UPDATE SET" in query
        assert "RETURNING unique_id" in query

    def test_execute_values_called_with_fetch_true(self, pg_manager, mock_pool, sample_news):
        """execute_values is called with fetch=True."""
        _, _, mock_cursor = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[],
        ) as mock_exec:
            pg_manager.insert(sample_news)

        assert mock_exec.call_args[1].get("fetch") is True or (
            len(mock_exec.call_args[0]) > 3 or mock_exec.call_args[1].get("fetch") is True
        )


# =============================================================================
# Inserted articles metadata
# =============================================================================


class TestInsertedArticlesMetadata:
    """Tests for the inserted_articles list contents."""

    def test_articles_contain_correct_metadata(self, pg_manager, mock_pool, sample_news):
        """Each article has required keys with values matching the original NewsInsert."""
        _, _, mock_cursor = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[("mec-2026-01-01-noticia-1",)],
        ):
            _, articles = pg_manager.insert(sample_news)

        article = articles[0]
        # Has required keys
        assert "unique_id" in article
        assert "agency_key" in article
        assert "published_at" in article
        # Values match input
        assert article["unique_id"] == "mec-2026-01-01-noticia-1"
        assert article["agency_key"] == "mec"
        assert article["published_at"] == datetime(2026, 1, 1, 12, 0, tzinfo=timezone.utc)

    def test_only_returned_ids_in_articles(self, pg_manager, mock_pool, sample_news):
        """Only IDs returned by RETURNING appear in inserted_articles."""
        _, _, mock_cursor = mock_pool

        # Only second article was actually inserted (first conflicted)
        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[("mds-2026-01-02-noticia-2",)],
        ):
            count, articles = pg_manager.insert(sample_news)

        assert count == 1
        assert len(articles) == 1
        assert articles[0]["unique_id"] == "mds-2026-01-02-noticia-2"
        assert articles[0]["agency_key"] == "mds"


# =============================================================================
# Deduplication
# =============================================================================


class TestInsertDeduplication:
    """Tests for in-memory deduplication before insert."""

    def test_deduplicates_by_unique_id(self, pg_manager, mock_pool):
        """Duplicate unique_ids are removed before insert."""
        _, _, mock_cursor = mock_pool
        dup_news = [
            NewsInsert(
                unique_id="dup-1",
                agency_id=1,
                title="First",
                published_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
            ),
            NewsInsert(
                unique_id="dup-1",
                agency_id=1,
                title="Duplicate",
                published_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
            ),
        ]

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            return_value=[("dup-1",)],
        ) as mock_exec:
            pg_manager.insert(dup_news)

        # Only 1 value tuple should be passed
        values = mock_exec.call_args[0][2]
        assert len(values) == 1

    def test_empty_list_raises(self, pg_manager):
        """Empty news list raises ValueError."""
        with pytest.raises(ValueError, match="cannot be empty"):
            pg_manager.insert([])


# =============================================================================
# Error handling
# =============================================================================


class TestInsertErrorHandling:
    """Tests for error handling in insert()."""

    def test_rollback_on_error(self, pg_manager, mock_pool, sample_news):
        """Connection is rolled back on error."""
        _, mock_conn, _ = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            side_effect=Exception("DB error"),
        ):
            with pytest.raises(Exception, match="DB error"):
                pg_manager.insert(sample_news)

        mock_conn.rollback.assert_called_once()

    def test_connection_returned_on_error(self, pg_manager, mock_pool, sample_news):
        """Connection is returned to pool even on error."""
        pool_obj, mock_conn, _ = mock_pool

        with patch(
            "govbr_scraper.storage.postgres_manager.execute_values",
            side_effect=Exception("DB error"),
        ):
            with pytest.raises(Exception):
                pg_manager.insert(sample_news)

        pool_obj.putconn.assert_called_once_with(mock_conn)
